# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - luciadevcontainer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f481cb9b9bc647b2bb894e2bc682e892 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e574eba9184c4160b9a633866b1e4583 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f481cb9b9bc647b2bb894e2bc682e892 }}/arjunsdev/luciabot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'luciadevcontainer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_17d85f0b99ca4ca092adb209b43d6170 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f481cb9b9bc647b2bb894e2bc682e892 }}/arjunsdev/luciabot:${{ github.sha }}'